%% Generated by the Erlang ASN.1 compiler version:3.0
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module AT-MESSAGE



-ifndef(_AT_MESSAGE_HRL_).
-define(_AT_MESSAGE_HRL_, true).

-record('LRQsNonStandardData',{
callerEndpointType}).

-record('LCFsNonStandardData',{
confID, destString = asn1_NOVALUE}).

-endif. %% _AT_MESSAGE_HRL_
