%% Generated by the Erlang ASN.1 compiler version:3.0
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module ConferenceBooking-MESSAGE



-ifndef(_CONFERENCEBOOKING_MESSAGE_HRL_).
-define(_CONFERENCEBOOKING_MESSAGE_HRL_, true).

-record('ARQsNonStandardData',{
sequenceNumber = asn1_NOVALUE, commandType, conferenceName = asn1_NOVALUE, conferenceDisplyName = asn1_NOVALUE, conferenceCtrlPassword = asn1_NOVALUE, conferencePassword = asn1_NOVALUE, conferencePayMethod = asn1_NOVALUE, startTime = asn1_NOVALUE, sessionTime = asn1_NOVALUE, multiPicture = asn1_NOVALUE, t120Conference = asn1_NOVALUE, h281 = asn1_NOVALUE, terminal = asn1_NOVALUE, dataRate = asn1_NOVALUE, qos = asn1_NOVALUE, cardNumber = asn1_NOVALUE, cardPassword = asn1_NOVALUE}). % with extension mark

-record('BookingTerminalInfo',{
terminalAddress, dataRate, terminalPayMethod = asn1_NOVALUE, portType = asn1_NOVALUE}). % with extension mark

-record('ACFsNonStandardData',{
sequenceNumber}).

-record('ARJsNonStandardData',{
sequenceNumber, errorReason = asn1_NOVALUE}). % with extension mark

-record('DRQsNonStandardData',{
sequenceNumber = asn1_NOVALUE, srcInfo, destInfo = asn1_NOVALUE, srcCallSignalAddress = asn1_NOVALUE, destCallSignalAddress = asn1_NOVALUE, srcType = asn1_NOVALUE, destType = asn1_NOVALUE, gkAddress = asn1_NOVALUE, conferenceName = asn1_NOVALUE, conferenceDisplyName = asn1_NOVALUE, startTime = asn1_NOVALUE, sessionTime, inBytes = asn1_NOVALUE, outBytes = asn1_NOVALUE, audioCodecType = asn1_NOVALUE, vedioCodecType = asn1_NOVALUE, t120CodecType = asn1_NOVALUE, terminationCause, serviceType = asn1_NOVALUE}). % with extension mark

-endif. %% _CONFERENCEBOOKING_MESSAGE_HRL_
