%% Generated by the Erlang ASN.1 compiler version:3.0
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module RASEXT-MESSAGE



-ifndef(_RASEXT_MESSAGE_HRL_).
-define(_RASEXT_MESSAGE_HRL_, true).

-record('RRQsNonStandardData',{
presenceService = asn1_NOVALUE, dualVideo = asn1_NOVALUE, extConfCtrl = asn1_NOVALUE, t120 = asn1_NOVALUE, updatable = asn1_NOVALUE}). % with extension mark

-record('RCFsNonStandardData',{
presenceServerAddr = asn1_NOVALUE, versionServerAddr = asn1_NOVALUE}). % with extension mark

-record('RRQNonStandardData',{
terStatusRequestNum, terStatusRequestList = asn1_NOVALUE}). % with extension mark

-record('RCFNonStandardData',{
terStatusResponseNum, terStatusResponseList = asn1_NOVALUE}). % with extension mark

-record('ConferenceStatusDescriptor',{
confStatus, conferenceAlias}). % with extension mark

-record('TerStatusDescriptor',{
terStatus, terNo}). % with extension mark

-endif. %% _RASEXT_MESSAGE_HRL_
